FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND noninteractive

ARG HTTPS_PROXY
ARG HTTP_PROXY

ENV http_proxy $HTTP_PROXY
ENV https_proxy $HTTPS_PROXY

RUN apt update && \
    apt install -y build-essential curl git pkg-config libfuse-dev fuse nodejs npm && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm@9

ARG TARGET_PLATFORM=s390x

RUN curl -vvv https://dl.google.com/go/go1.22.10.linux-$TARGET_PLATFORM.tar.gz | tar -xz -C /usr/local
ENV PATH="/usr/local/go/bin:${PATH}"
ENV GOCACHE=/tmp/go-build
ENV GOPATH=/tmp/go

LABEL org.opencontainers.image.source https://github.com/chaos-mesh/chaos-mesh

